### ISSUE TITLE
External file with translations

### ISSUE THREAD

**Issue by jdriesen** [dkfbasel/vuex-i18n#10]
Hello,

I have a small question.
You're writing
```
// translations can be kept in separate files for each language
// i.e. resources/i18n/de.json.
```
Can you please tell me how to 'load' such an external file ?

Thanks in advance for your reply & help,
Johnny

**Comment by tikiatua** [comment]
Hi @jdriesen ,

You can find an example in the test directory. Basically you just need to load the file via ajax and pass the translations to the plugin.

Please note, that the example is still using vue-resource. This library has been recently depreciated and it is recommended to switch to another ajax library. The authors recommend axios (which we are using now for all new projects).

```javascript
// code using vue-router
this.$http.get(url).then((response) => {
	return response.json();
}).then((data) => {
	this.$i18n.add(locale, data);
	this.$i18n.set(locale);
}).catch((error) => {
	alert('could not fetch locale translations');
});


// code using axios (do not forget to import axios)
// import axios from 'axios';
axios.get(url).then((response) => {
	this.$i18n.add(locale, response.data);
	this.$i18n.set(locale);
}).catch((error) => {
	alert('could not fetch locale translations');
});
```

Let me know if you need some further assistance.

**Comment by jdriesen** [comment]
Super.
Thanks a lot.
Gonna give it a try asap.
Thanks for your time to give me a reply. Appreciated !

Kind regards,
Johnny
