### ISSUE TITLE
What is the current version?

### ISSUE THREAD

**Issue by dmcdonald8** [dkfbasel/vuex-i18n#101]
I was under the impression v1.10.7 was the latest version? I believe the latest version added a config option to suppress warnings, which is what I need, but on npmjs the latest version is v1.10.5 which is 2 years old. If I try to upgrade the package using Yarn I'm told that 1.10.5 is the latest version available.

**Comment by tikiatua** [comment]
Hi @dmcdonald8,

Thank you for reporting this. I completely forgot to push the newest version to npm. Will do this right now.

**Comment by tikiatua** [comment]
Hi again,

newest version 1.10.7 is now on npm

**Comment by dmcdonald8** [comment]
@tikiatua 
Thank you!
