### ISSUE TITLE
Single File Component Children not updating

### ISSUE THREAD

**Issue by jan-thoma** [dkfbasel/vuex-i18n#108]
Steps to reproduce:

- Create a new new project with Vue-CLI3 with router and i18n
- Enable single file component Support
- Add  <i18n></i18n> to parent single file component which contains the vue-router outlet
- Add a watcher for '$18n.locale' to child component
- Update locale
- Nothing happens

**Comment by tikiatua** [comment]
Dear @jan-thoma 

Thank you for reporting this. For reactive updates you should watch the state directly. I.e. the locale property in the i18n module in the store.

The properties on the $i18n object are regular functions and not reactive properties.

**Comment by tikiatua** [comment]
The setup is actually for vue-i18n and not for vuex-i18n.
