### ISSUE TITLE
Extracting of strings

### ISSUE THREAD

**Issue by Remo** [dkfbasel/vuex-i18n#13]
I tried to figure out a way to automatically extract strings. There are a number of tools, some for angular, some make file based tools, so far I only tried to get this running as it seemed easy enough to customize https://github.com/flozz/stonejs-tools

I managed to get something extracted by running this command:

`stonejs extract "dist/**/*.js" file.pot --functions="$t"`

The summary so far:

* It does extract functions, tlang and so on would also work
* Not sure how to extract ` | translate`, not sure I would use that though
* stonejs doesn't parse my ES6 code, I had to run it on top of my dist files which makes the references in the pot file a bit silly
* I have to convert the POT file to a JSON file, there are a lot of tools for this, it's just another step

This feels a bit cumbersome, did anyone try something like this?

**Comment by tikiatua** [comment]
Hi there. I will close this issue as it is not directly related to the vuex-i18n plugin
