### ISSUE TITLE
Using $t() outside of component - in service

### ISSUE THREAD

**Issue by Arxi** [dkfbasel/vuex-i18n#16]
Is it possible to somehow import the $t() method so that it can be used outside of component, i.e. in a custom service? By service I mean a set of methods in a separate file, not tied to any Vue component.

Thanks!

**Comment by tikiatua** [comment]
Hi @Arxi,

Thank you for your question. This should actually be possible by using the methods that are placed directly on the global vue instance. The $t method in the instance is available as Vue.i18n.translate.

```javascript
Vue.i18n = {
	locale: getLocale,
	set: setLocale,
	add: addLocale,
	remove: removeLocale,
	fallback: setFallbackLocale,
	exists: checkLocaleExists,
	translate: translate,
	translateIn: translateInLanguage
};

// the translation method can be called using
Vue.i18n.translate(..)
```
Please let me know if this works for you.

**Comment by Arxi** [comment]
Thank you, it does! For future reference, here's how I use it in a service called `userMessages.js`:

```javascript
import Vue from "vue";
import apiDefinition from 'src/config/apiDefinition';

function afterResetPassword(response) {
    let message = "";

    switch (response.status) {
        case apiDefinition.codes.ok :
            message = Vue.i18n.translate('RESET_PASS_SUCCESSFUL');
            break;
        case apiDefinition.codes.unprocessableEntity :
            message = Vue.i18n.translate('RESET_PASS_FAILED_VALIDATION');
            break;
        case apiDefinition.codes.internalServerError :
        default :
            message = Vue.i18n.translate('RESET_PASS_FAILED_ERROR');
            break;
    }

    return message;
}

export default {
    afterResetPassword
};
```

and then 
```javascript
import userMessages from "src/services/userMessages";

console.log(userMessages.afterResetPassword(response));
```

**Comment by gmsa** [comment]
Does this still work?

**Comment by drognisep** [comment]
@Arxi @tikiatua 
I'm having a similar issue, but the solution above doesn't seem to work. I'll illustrate my context so I can also be told if I'm doing something silly in the initialization. I'm kicking this off in development mode with `npm run serve` which calls `vue-cli-service serve --host localhost --port 4200`.

It seems likely that something changed between 2017 and now, so I'm assuming I'm just missing something obvious. I haven't found anything that specifically addresses this in the docs, so I'm kind of at a loss.

```javascript
// Full app initialization
import Vue from 'vue';
import App from './App.vue';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import BootstrapVue from 'bootstrap-vue';
import router from './router.js';
import VueI18n from 'vue-i18n';
import messages from './assets/messages.json';

Vue.config.productionTip = false;
Vue.use(BootstrapVue);
Vue.use(VueI18n);

let locale = navigator.language;

// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: locale, // set locale
  messages // set locale messages
});

new Vue({
  router,
  i18n,
  render: h => h(App)
}).$mount('#app');
```

Now attempting to apply the solution above.
```javascript
// This is a plain javascript file called statuses.js imported by a Vue component
import Vue from 'vue';

// Prints out 'undefined' as expected
console.log($t);

// Attempt to define `$t` in this context
const $t = Vue.i18n.translate; // `Vue.i18n` is undefined here, so this results in a TypeError
```

**Comment by danielskeeled** [comment]
@drognisep did you manage to solve it?

**Comment by gmsa** [comment]
@danielskeeled you have to import the i18n instance you created and use that:

```javascript
// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: locale, // set locale
  messages // set locale messages
});
```

And on the other file:

```javascript
import {i18n} from "./i18nInstanceFile";

i18n.tc('text.key');

```

**Comment by drognisep** [comment]
> @drognisep did you manage to solve it?

Hey! Sorry for the late response. Yes I just used a very similar pattern to what @gmsa recommended and it works like a charm. Thanks! 👍

**Comment by serdarde** [comment]
@gmsa 's answer has solved my problem, but I had to use like this in vue 3:

    i18n.global.tc('text)

**Comment by yabuking84** [comment]
i18n.global.tc('text) shows error "Type instantiation is excessively deep and possibly infinite."

**Comment by justforuse** [comment]
I have to use `const translate = window.i18n.tc.bind(window.i18n)` in my project. Otherwise it will report `can not read property _tc of undefined`

**Comment by fabus961** [comment]
How bout this approach w. vue3 composition api
_"vue": "^3.0.0",
"vue-i18n": "^9.1.10",_

in my **config.ts** I export the i18n const for setup and $t as global helper

```javascript
import {createI18n} from "vue-i18n";
import deDE from "@/core/i18n/locales/de-DE.json";
import enUS from "@/core/i18n/locales/en-US.json";
import cnCN from "@/core/i18n/locales/cn-CN.json";

const i18n = createI18n({
    legacy: false,
    locale: 'de-DE',
    fallbackLocale: 'en-US',
    globalInjection: true,
    messages: {
        'de-DE': deDE,
        'en-US': enUS,
        'cn-CN': cnCN
    },
   ... more config stuff
    }
})

const $t = i18n.global.t

export { i18n, $t };
```

use in  **main.ts**
```javascript
import { i18n } from "@/core/i18n/config";
app.use(i18n);
```

use in script file
```javascript
import { $t } from "@/core/i18n/config";
console.log('Print OKAY: ', $t("common.ok"))
```
