### ISSUE TITLE
"minified" distribution is not minified

### ISSUE THREAD

**Issue by SirLamer** [dkfbasel/vuex-i18n#18]
Just a heads-up.

**Comment by tikiatua** [comment]
Hi @SirLamer,

Thanks for your comment. Did not realize that until now. Should we rather rename it to umd or actually minify the file.

**Comment by SirLamer** [comment]
I suggest you publish both cases. In development environments, the dev build will pull the non-minified version and the production build will take the minified one.

**Comment by tikiatua** [comment]
I finally managed to do this. There is now a new vuex-i18n.umd.js file and the vuex-i18n.min.js is a minified version of this. Will release this later today
