### ISSUE TITLE
Customizable placeholder marker in translation dyamic parameters

### ISSUE THREAD

**Issue by germanp** [dkfbasel/vuex-i18n#21]
Is there any chance to support parametrizing the placeholder syntax for dynamic translations? In the project I'm working we already use double braces (`{{ }}`). Eg.:

`{{ $t('You have {{count}} new messages', {count: 5}) }}`

So, should be great to configure {{ and }} as the separators instead of just { and }

Cheers

**Comment by tikiatua** [comment]
Hi @germanp 
This is certainly a prominent use case. We added the feature in version 1.3.6
