### ISSUE TITLE
pb de translate

### ISSUE THREAD

**Issue by nlefebvre1410** [dkfbasel/vuex-i18n#24]
hi,
I have my translation in ajax.
On my home if the component is static the translation is not done.
Thank you for your help
main.js
```javascript
  methods: {
    starttrans () {

      this.$http.get('/locale-en.json')
        .then(response => response.data)
        .then(function (data) {
          Vue.i18n.add('en', data)
        })
        .catch(function (response) {
          console.log(response)
        })
    }
  },
  created () {
    Vue.i18n.set('en')
    console.log('monted')
    this.starttrans()
  }`

component test.vue

<template>
<div>
  <div class="box-tab">
    {{getIdStore}}
    <div class="">

{{ $tlang($i18n.locale() , 'asset.class') }}
{{ $t('asset.name') }}
{{ $tlang($i18n.locale() , 'asset.gegraphical') }}
  {{ $tlang($i18n.locale() , 'asset.devise') }}
   

    </div>
  </div>
</div>
</template>
<script>
  import Vue from 'vue'
  import Vuex from 'vuex'
  Vue.i18n.set('en')
  Vue.i18n.fallback('en')
module.exports = {
    data: function () {
      return {

      }
    },
    computed: {
      ...Vuex.mapGetters([
        'getIdStore',
        'getSlider'
      ])
    },
    methods: {
    }
}
</script>
```

**Comment by tikiatua** [comment]
Hi @nlefebvre1410 

Thank you for your question. As I can glance from your code, I am not sure if you are initializing the plugin correctly. Please see the example below on how to do so. You must initialize the sore first and then pass the store the the plugin using the method `Vue.use(vuexI18n.plugin, store)`. 

```javascript
// load vue and vuex instance
import Vue from 'vue';
import Vuex from 'vuex';

// load vuex i18n module
import vuexI18n from 'vuex-i18n';

// initialize the vuex store using the vuex module. note that you can change the
//  name of the module if you wish
const store = new Vuex.Store();

// initialize the internationalization plugin on the vue instance.
Vue.use(vuexI18n.plugin, store);
```
Please let me know, if this solves your problem.

**Comment by nlefebvre1410** [comment]
yes ,
Here is the complete hand:
`import Vue from 'vue'
import Vuex from 'vuex'
import VueAwesomeSwiper from 'vue-awesome-swiper'
import jQuery from 'jquery'
import VueHighcharts from 'vue-highcharts'
import store from './store'
import vuexI18n from 'vuex-i18n'
import axios from 'axios'
import VueFormGenerator from 'vue-form-generator/dist/vfg-core.js'
import 'vue-form-generator/dist/vfg-core.css'

Vue.filter('currency3', function (value) {
  value = parseFloat(value)
  if (!isFinite(value) || (!value && value !== 0)) return ''
  var stringified = Math.abs(value).toFixed(0)
  return stringified + '%'
})
const stores = new Vuex.Store()
// Vue.use(Vue2Filters)
Vue.use(VueFormGenerator)
Vue.use(VueHighcharts, { Highcharts })
Vue.use(VueAwesomeSwiper)
Vue.use(vuexI18n.plugin, stores)

var Highcharts = require('highcharts')
require('highcharts/highcharts-more.js')(Highcharts)
window.jQuery = window.$ = jQuery
require('bootstrap-sass')

// Vue.config.delimiters = ['@{', '}']
// Vue.config.productionTip = false

Vue.component('app', require('./components/App'))
Vue.component('slides2', require('./components/Slides2.vue'))
Vue.component('bar', require('./components/charts/bar.vue'))

Vue.prototype.$http = axios

/* eslint-disable no-new */
new Vue({  // eslint-disable-line no-new
  el: '#app',
  store,
  stores,
  jQuery,
  methods: {
    starttrans () {
      // const TRANS = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '') + '/' + this.$i18n.locale() + '/trans/json'
      // let $this = this
      this.$http.get('/locale-en.json')
        .then(response => response.data)
        .then(function (data) {
          Vue.i18n.add('en', data)
        })
        .catch(function (response) {
          console.log(response)
        })
    }
  },
  created () {
    Vue.i18n.set('en')
    console.log('monted')
    this.starttrans()
  }
})

`

**Comment by tikiatua** [comment]
Hi again,

Unfortunately, I am not able to replicate your problem (see code below, that is working as expected, albeit using vue-resource instead of axios). 

Please make sure you are using the latest version of the vuex-i18n plugin (v1.4.1). You also seem to have multiple store attributes that you pass to the Vue instance (store and stores). Maybe this could lead to a conflict?

```javascript
// enable the vue devtools
Vue.config.devtools = true;

// initialize a new vuex store including our i18nVuexModule
const store = new Vuex.Store();

// initialize the vuexi18nPlugin
Vue.use(vuexI18n.plugin, store);

// use the plugin methods to access and add translations
var app = new Vue({
	store,
	el: '#app',
	created() {
		Vue.i18n.set('de');
		this.fetchTranslations();
	},
	methods: {

		// enable language changing
		fetchTranslations() {

			let url = '/test/locale-de.json';

			// load the specified locale from the server
			this.$http.get(url).then((response) => {
				return response.json();

			}).then((data) => {
				Vue.i18n.add('de', data);

			}).catch((error) => {
				alert('could not fetch locale translations');
			});

		}
	}
});
```
