### ISSUE TITLE
dist/vuex-i18n.min.js(new build 13 days ago) has a problem

### ISSUE THREAD

**Issue by justinFather** [dkfbasel/vuex-i18n#25]
Sorry, I didn't capture the error messages.

Im using vuex-i18n in nuxt framework. Nuxt gave me the errors related with vuex-i18n.

It said the errors occurred in ADD_LOCALE.

I thought it was caused by 'flattenTranslations' and it was pointing the field of 'undefined'.

I saw the message at the time, but it was bundled by nuxt. so the field name is not the original one.

Anyway I fixed it with replacement it with your older vuex-i18n.min.js.

If it's possible please make it fixed. Thanks

**Comment by tikiatua** [comment]
Hi @justinFather,

I just pushed a new version (1.4.3) that should fix the issue. It could have to do with the version of vuex that you are using.
