### ISSUE TITLE
i18nVuexModule is not defined

### ISSUE THREAD

**Issue by arddor** [dkfbasel/vuex-i18n#3]
I noticed that the `i18nVuexModule` (the store definition) is missing in the commonjs file. Could you rebuild it and publish on NPM?

**Comment by tikiatua** [comment]
Hi there,
Thank you for the information. I just rebuilt the package and published version 1.2.2 hope this will fix the issue. Let me know if it still doesn't work.

**Comment by arddor** [comment]
Thank you it works now.
