### ISSUE TITLE
about date localization

### ISSUE THREAD

**Issue by HDP2017** [dkfbasel/vuex-i18n#31]
Can support it, how to achieve it？

**Comment by tikiatua** [comment]
Hi @HDP2017,

That is a good question. Date localization is actually very tricky on its own. For now, I would suggest to use a library such as moment.js to localize the date string and then pass it to the translation as a placeholder.

`<p>$t('post.date', 'You posted this on {date}', {date: localize(datevalue)})</p>`

The localize method should be added as method to the respective component – or added as separate vue plugin if you like to use it in multiple components. You could then use the method this.$i18n.locale to fetch the current locale and format the date string accordingly.

This would add the additional benefit, that you could also create "humanized" dates such as "three minutes ago".

**Comment by HDP2017** [comment]
moment.js!!! In fact, my project using the plug-in, everything is a matter of course, thank you
