### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by jniyaz** [dkfbasel/vuex-i18n#32]
Cannot read property 'split' of null at translateInLanguage.. in Vue- Quasar framework.. any solutions?

**Comment by jniyaz** [comment]
it works now. default language setup issue, main.js updated.

**Comment by kosirm** [comment]
I would like to use vuex-i18n with quasar, but don't know where to start properly... Do you maybe know for some example quasar project?

**Comment by tikiatua** [comment]
Hi @kosirm 

Unfortunately, there is currently no quasar example that I know of. However, there is a todo example in the directory /examples/todo with the main starting file at https://github.com/dkfbasel/vuex-i18n/blob/master/examples/todo-vuex-i18n/src/app/main.js.

Maybe just take a look at the example repository to find out how it works, or there is also a presentation https://github.com/dkfbasel/vuex-i18n/blob/master/examples/vuex-i18n.pdf which shows you how to use vue-i18n (a different library) and vuex-i18n. 

Please let me know, if this does not work out.
