### ISSUE TITLE
vuexI18n Error in render function: "TypeError: Cannot read property 'split' of null"

### ISSUE THREAD

**Issue by nnjeim** [dkfbasel/vuex-i18n#39]
Hi all,

i am using the following <label>{{ $t('name') }}</label>
in some components i am getting the subject error in some other it is working.
the translation is being printed correctly but the i am getting the error in the console.
Anyone to advise please.

**Comment by tikiatua** [comment]
Hi @nnjeim, 

Could you maybe post your setup code? Maybe the translation is not yet loaded when you try to access the key?

**Comment by tikiatua** [comment]
It could also have to do with the locale not being specified yet.

**Comment by nnjeim** [comment]
Hi, 
 
the translation files are mounted in the window as window.locales and i managed to make it work by 
calling i18n from beforeMount, it is working now.... any best practice to share here?
thanks a lot,

 beforeMount () {

    this.$foreach(window.locales, (labels, locale) => {
      this.$i18n.add(locale, labels);
    });

    this.$i18n.set(window.Locale.lang);
  }

**Comment by tikiatua** [comment]
Hello @nnjeim,

I will try to add a fix to the plugin in the upcoming days, that will make sure that no error is thrown if this situation happens.

**Comment by tikiatua** [comment]
Hi @nnjeim,

I added a corresponding fix and will push an updated version sometime today.
