### ISSUE TITLE
translate placeholder html tag

### ISSUE THREAD

**Issue by nnjeim** [dkfbasel/vuex-i18n#40]
Hi,

How to translate a placeholder i have tried  placeholder="{{ $t('placehoder') }}"
i also tried placeholder="{{ 'placeholder' | translate }}"

please advise

**Comment by galchenkov** [comment]
`<input :placeholder="$t('placeholder')">`

**Comment by lostinlight** [comment]
Hi everyone, 
many thanks to the author for the plugin.

If I'm not mistaken, there're no getters or method in the store to retrieve all available locales. What's the most appropriate "vuex way" to get that data to display in templates? 

All I can think of is:
`const locales = Object.keys(this.$store.state.i18n.translations)`

Didn't want to open a separate issue for this one, sorry for hijacking yours, @nnjeim

**Comment by tikiatua** [comment]
Hi @lostinlight,

your suggestions seems about right. Basically we simply store an object with the translations in the vuex store and you are free to access the data any way you like.

We could also add an array to keep track of the locales that have been added to the store, but this might be overkill.

**Comment by lostinlight** [comment]
@tikiatua Thank you!
