### ISSUE TITLE
Suggestion: add link to locale-man :)

### ISSUE THREAD

**Issue by chlab** [dkfbasel/vuex-i18n#47]
Hey guys

Thanks for your great library! I've used it before in a large project and before I use it again, I figured I would write a little helper for adding translations: [here](https://github.com/liip-amboss/locale-man).

If you deem it useful, feel free to link it in your Readme. I'll add functionality as I need it (e.g. removing/updating translations, ordering the translation files alphabetically, maybe syncing with the poeditor.com API, etc.). Contributions are welcome!

Cheers and thanks

**Comment by tikiatua** [comment]
Hi @chlab

Many thanks for developing this utility. This will come in very handy on our next project. I added a respective section to the readme.
