### ISSUE TITLE
Method for accessing translations within methods

### ISSUE THREAD

**Issue by Buzut** [dkfbasel/vuex-i18n#49]
Hi,

Thank you for this great module. Correct me if I'm wrong, but there's not builtin method to access a given translation from within methods.

For instance, if I want to pass a translated text to some functions, the only way to do it is directly via the store:

```
methods: {
  displayNotification() {
    this.$notify(this.$store.state.i18n.translations[this.$store.state.i18n.locale].notificationString);
  }
}
```

It would be awesome to have a helper method for that. Like `this.$i18n.translate('blabla');`

**Comment by tikiatua** [comment]
Hi Buzut,

There is a helper function for that. You should be able to get the translation with `this.$i18n.t('blabla')`. 

We should probably add this to the readme and make the same function accessible with this.$i18n.translate.

**Comment by tikiatua** [comment]
Oh, sorry, small correction.. you need to use `this.$t('blabla')` to access the translation.

**Comment by Buzut** [comment]
Awesome thank you. As it wasn't in the readme, I inferred that it didn't exist. I should have given a look at the source :)
