### ISSUE TITLE
Flattened Lists

### ISSUE THREAD

**Issue by nkoehring** [dkfbasel/vuex-i18n#5]
Currently, the flattenTranslations function also flattens lists. For example:

```json
"some.key" : ["some", "list", "of", "values"]
```

is flattened to

```json
"some.key.0" : "some",
"some.key.1" : "list",
"some.key.2" : "of",
"some.key.3" : "values"
```

When translating longer paragraphs (Terms&Conditions for example) it is nice to just have a list of them without having to know how many entries that list has. I also don't see any other reason why a list should be flattened.

I vote for keeping lists in. I can also create a PR for this.

**Comment by tikiatua** [comment]
Hi @nkoehring,

Thank you for raising this issue. We actually never thought about this use case. I will adapt the flattenTranslations function to not flatten arrays and see where this will take us. 

We should probably also think about how objects in an array should be handled.

```javascript
"some.key" : [
    {title: "title one", content: "some content"},
    {title: "title two", content: {name: "myname"}}
]

// should probably be transformed to
"some.key": [
    {title: "title one", content: "some content"},
    {title: "title two", "content.name": "myname"}}
]
```

**Comment by nkoehring** [comment]
I see where you want to go but I wonder if this is really worth much additional work. I can't imagine a reason why people should create such a data structure for their translations. Do you know any example? Would be interesting to see.

**Comment by tikiatua** [comment]
Cannot really think of an example. I just added the changes and pushed it to npm as version 1.3.0. We assume, that lists would usually be composed only of strings. Therefore we added a console warning if this is not the case. For list of strings variable replacements are supported as usually.
