### ISSUE TITLE
pluralization placeholder not translated

### ISSUE THREAD

**Issue by Buzut** [dkfbasel/vuex-i18n#56]
Hi,

I'm trying to use pluralization but althouhg I get the correct placeholder (singular and plural based on context), it doesn't get translated.

```
{{ mutualFriends }} {{ $t('friend_in_common ::: friends_in_common', {}, mutualFriends) }}
```

For instance, for mutualFriends with values of 1 and 2 I get either 

__1 friend_in_common__ 

or 

__2 friends_in_common__

but not the translated text.

I use the lastest npm version, namely 1.8.0. Config is as follows:

```
import vuexI18n from 'vuex-i18n';
import store from './store/index';
import english from './assets/lang/en.json';
import french from './assets/lang/fr.json';

Vue.use(vuexI18n.plugin, store);
Vue.i18n.add('en', english);
Vue.i18n.add('fr', french);
```

No error is raised.

Thanking you in advance :)

**Comment by tikiatua** [comment]
Hi @Buzut 

Thank you for reporting this. We originally started out from using translations strings directly instead of using keys to look up translations. The behavior that you reported is probably a residual from this.

I will look into the issue tomorrow.

**Comment by Buzut** [comment]
Hey @tikiatua,

Once again, thank you for your prompt answer! 
Hope you'll be able to solve this without much hassle.

I really loving your plugin, so simple and efficient, thank you for this.

**Comment by tikiatua** [comment]
Hello @Buzut 

I did look into the problem and checked our documentation and tests again.

Basically you need to either specify the text to translate directly instead of using a key to lookup a reference:
`{{ $t('You have {count} new message ::: You have {count} new messages', {count: 5}, 5) }}`

Or you specify a key that will contain all translations
```javascript
{{ $t('plural', {count: count}, count) }} 

// with plural being specified with all translations
"plural" = "You have {count} new message ::: You have {count} new messages"
```

Is this sufficient for your use case or do you think we should add a lookup of the separate pluralization parts?

**Comment by Buzut** [comment]
Hello,

Thank you for your detailed answer. Actually, it works as expected. The problem I had was that the `count` variable was returned as a String by the API. 

`parseInt` fixed the problem.
```
{{ $t('plural', {count: parseInt(count)}, parseInt(count)) }}
```
Having the plural forms specified within the same translation string is even better as it's less verbose in the code.

It perfectly fits my use case, so there's nothing to be added.

Again, thank you very much for your help.
