### ISSUE TITLE
Send missing keys to API service

### ISSUE THREAD

**Issue by jernejrostan** [dkfbasel/vuex-i18n#59]
Hi,

I have a question more then issue.
I know about  **onTranslationNotFound** but i wonder if there is anyway to watch or observe for missing keys during use of some webpage.

I can get a collection of all missing keys on load, but i do have some missing keys while using webpage. For example some notifications that are launched during usage. And if key is missing i would just send this key to my API service. 
I'm asking because i'm not translating webpage, webpage is in multiple languages and this would be quite useful feature. Well at least for me at the moment :)

Thanks!

**Comment by tikiatua** [comment]
Hi @jernejrostan 

Thank you for your input. This is a use case we did not consider before. I adapted the plugin and just published a new release (v1.10.1) that will allow you to do so. 

Basically it comes down to updating the translations in the store on the fly. This can be achieved via the method Vue.i18n.addLocale or by dispatching the action store.dispatch('i18n/addLocale'). The addLocale method will update the respective locale in the store and keep all existing translations for the locale.

Here is an example of this:
```javascript
onTranslationNotFound: function(locale, key) {

  window.setTimeout(() => {
    store.dispatch('i18n/addLocale', {
      locale: 'en',
      translations: {'async.promise': 'This translation is resolved asynchronously'}
    });
  }, 1000);

  console.warn(`vuex-i18n :: Key '${key}' not found for locale '${locale}'`);
}
```

However we built-in some convenience methods to allow you to just directly return the new translation from the method. If the value is resolved asynchronously, you need to return a promise.

```javascript
// with string as return value. this will write the new value as translation
// into the store
// note: synchronous resolving of keys is not recommended as this functionality
// should be implemented in a different way
Vue.use(vuexI18n.plugin, store, {
  moduleName: 'i18n',
  onTranslationNotFound (locale, key) {
    switch(key) {
    case: '200':
      return 'Everything went fine';
      break;
    default:
      return 'There was a problem';
    }
  }}
);

// with promise as return value. this will write the new value into the store,
// after the promise is resolved
Vue.use(vuexI18n.plugin, store, {
  moduleName: 'i18n',
  onTranslationNotFound (locale, key) {

    return new Promise((resolve, reject) => {
      axios.get('/api/translations/async', {locale: locale, key:key})
      .then((result) => {
        resolve(result.data);

      }).catch() {
        reject();
      }
      
    })

  }}
);
```

There is also a small demo in the test directory. Please try it out and let us know if this works for you.

**Comment by jernejrostan** [comment]
Nice, will try it out soon :)

**Comment by jernejrostan** [comment]
Works like a charm :)
