### ISSUE TITLE
Allow pluralizations

### ISSUE THREAD

**Issue by phouverneyuff** [dkfbasel/vuex-i18n#6]
Will be interesting some way to pluralizate like https://kazupon.github.io/vue-i18n/pluralization.html

**Comment by tikiatua** [comment]
Hi @phouverneyuff,
thank you for your input. Pluralization is actually quite a difficult topic, especially with languages other than english. 

We might have to investigate this a little further, if we want to include this into the library. The solution provided by vue-i18n might be a little crude for most real life requirements.

**Comment by phouverneyuff** [comment]
We could almost allow pluralizations to english, portuguese, spanish that are easy to pluralizate.
I think only this will help many peoples even not helping with another languagues.

In my case, using something like in https://kazupon.github.io/vue-i18n/pluralization.html would help me.

**Comment by phouverneyuff** [comment]
Here the code that allow pluralization:
https://github.com/kazupon/vue-i18n/blob/dev/src/extend.js#L18

**Comment by tikiatua** [comment]
P.S. Pluralization is now supported - albeit a little bit different then in vue-i18n. Please see in the readme for a usage example.
