### ISSUE TITLE
vuex-i18n install error

### ISSUE THREAD

**Issue by haijingsea** [dkfbasel/vuex-i18n#65]
I have a project which is running normal,but I import vuex-i18n module,compile is Ok,but I find a issue when I refresh the browser,I need your help ,thank you.
![codepng](https://user-images.githubusercontent.com/34846541/35140282-9a5c4948-fd31-11e7-9999-1ba76431c8b8.png)
![issue](https://user-images.githubusercontent.com/34846541/35140433-2801f234-fd32-11e7-8baa-3d3bcd9daa83.png)

**Comment by tikiatua** [comment]
Hi @haijingsea,

This error is usually occurring if your code contains es2015 javascript that has not been transpiled by babel and is not yet supported in your browser.

The solution is to either include the vuex-i18n in your transpilation pipeline or to use the transpiled and minified version like this:

```javascript
import vuexI18n from 'vuex-i18n/dist/vuex-i18n.umd.js';
```

There is a small section in the readme about this. Maybe it is not yet clear enough. 

```javascript
// current part of the readme:
// please note that the default format for the plugin is in es2015
// for use in server side rendering (such as nuxt), the umd version should be loaded like this
import vuexI18n from 'vuex-i18n/dist/vuex-i18n.umd.js';
```
