### ISSUE TITLE
Translations from API service

### ISSUE THREAD

**Issue by jernejrostan** [dkfbasel/vuex-i18n#67]
Hi, 

Maybe i cant find it, so i am asking here. Is there anyway to load translations before rendering?
I load translations from service, but i do get like 300 Warnings before that (understandable)

Maybe im missing something.

Thanks

**Comment by tikiatua** [comment]
Hi @jernejrostan 

Please take a look at the file index.hml in the test directory. The method to fetch translations from an api service if the key is not found is only intended as fallback if all other measures fail. Usually you should prefetch the data when starting the application or in a route guard.

Please let me know if you need any further assistance.

**Comment by jernejrostan** [comment]
hi @tikiatua 

Yeah im tryin to figure out how to load everything in **beforeEnter** and i still get all the warnings. Any ideas?

**Comment by tikiatua** [comment]
Could you post the code used in the beforeEnter hook? It could be possible, that you are using a promise to resolve the data and the component is rendered before the data actually arrives.

**Comment by jernejrostan** [comment]
yeah had some typos :) solved stuff, so now working as expected
