### ISSUE TITLE
Some browsers on the mobile side can not be used,such as  Some browsers on the mobile side can not use uc browsers etc...

### ISSUE THREAD

**Issue by phunsuke** [dkfbasel/vuex-i18n#68]
After using this plugin, the browser on the computer side is good, but some browsers on the phone side are not available. Opera, chrome, firefox are all available but some of China's native browsers are not available. Look forward to you can solve this problem

**Comment by tikiatua** [comment]
Hi @phunsuke 

Thank you for reporting this. This is clearly an important issue. This is probably an issue with the rendering cycle.

We will be able to look into the problem in the UC browser on iOS. Unfortunately it is very difficult for us to pinpoint the problem in any of China's native mobile browsers as we are based in Switzerland and have no respective testing devices available to us.

Do you have any idea how we could investigate the problem any further or can you provide some more details on what the problem is in detail (i.e. default string is rendered or nothing is rendered)?

**Comment by phunsuke** [comment]
Rendering effects is just like uc browser. Can not switch, nor render the correct language. Because in the mobile browser, I temporarily no way to find out the reason

**Comment by phunsuke** [comment]
my project use the requirejs + vue combination, when i use this plugin, the page is nothing but white screen directly.

**Comment by alphaCastor** [comment]
The same problem. Tested on iPhone 4s. 
If you have mac, you can add custom user agent  in Safari to reproduce this bug:

`Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B179 Safari/7534.48.3`

No errors on console. Empty page.

**Comment by tikiatua** [comment]
Could be the issue referenced here https://github.com/requirejs/requirejs/issues/1234

**Comment by alphaCastor** [comment]
Hi again. Thank you for your react reply. I reproduced bug. There are my
steps to reproduce it.

1. I created new vue project via vue-cli (vue init webpack-simple)
2. Then to connect from my iphone i added line in dev script
(192.168.100.11 - my local IP):
"scripts": {
"dev": "cross-env NODE_ENV=development webpack-dev-server --inline --port
8080 --host 192.168.100.11 --content-base .",
"build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
}

3. In main.js file i added vuex and vuex-i18n

import Vue from 'vue';
import Vuex from 'vuex';
import vuexI18n from 'vuex-i18n';
import App from './App.vue';

Vue.use(Vuex)

const store = new Vuex.Store();
Vue.use(vuexI18n.plugin, store);

const translationsEn = {
  "content": "This is some {type} content"
};

const translationsDe = {
  "My nice title": "Ein schöner Titel",
  "content": "Dies ist ein toller Inhalt"
};


Vue.i18n.add('en', translationsEn);
Vue.i18n.add('de', translationsDe);

Vue.i18n.set('en');


new Vue({
store,
el: '#app',
render: h => h(App)
})

4. Result is blank page

I hope this will help us to find any solution to make vuex-i18n capability
with old safari versions :)

2018-02-27 16:25 GMT+02:00 Ramon Saccilotto <notifications@github.com>:

**Comment by alphaCastor** [comment]
Hi again. Thank you for your react reply. I reproduced bug. There are my
steps to reproduce it.

1. I created new vue project via vue-cli (vue init webpack-simple)
2. Then to connect from my iphone i added line in dev script
(192.168.100.11 - my local IP):
```
"scripts": {
"dev": "cross-env NODE_ENV=development webpack-dev-server --inline --port
8080 --host 192.168.100.11 --content-base .",
"build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
}
```

3. In main.js file i added vuex and vuex-i18n

```
import Vue from 'vue';
import Vuex from 'vuex';
import vuexI18n from 'vuex-i18n';
import App from './App.vue';

Vue.use(Vuex)

const store = new Vuex.Store();
Vue.use(vuexI18n.plugin, store);

const translationsEn = {
  "content": "This is some {type} content"
};

const translationsDe = {
  "My nice title": "Ein schöner Titel",
  "content": "Dies ist ein toller Inhalt"
};


Vue.i18n.add('en', translationsEn);
Vue.i18n.add('de', translationsDe);

Vue.i18n.set('en');


new Vue({
store,
el: '#app',
render: h => h(App)
})
```

4. Result is blank page

I hope this will help us to find any solution to make vuex-i18n capability
with old safari versions :)

**Comment by vuduongq** [comment]
Hi all.

Is not a vuexI18n problem but a vuex problem in general of the UC browser.

Vuex uses promises but the UC browser does not support promise at default.
See the issue in the [vuex github repo](https://github.com/vuejs/vuex/issues/519).

Using a polyfill should solve your problem.

`https://cdn.polyfill.io/v2/polyfill.min.js?flags=gated&unknown=polyfill`

For the UC browser you also have to set additional polyfill params:

`flags=gated` to avoid override of native implementations
`unknown=polyfill` to use polyfill for unrecognized user-agents what in this case the UC browser is.

Here is an example running on my Android test environment using the latest version of the UC browser:
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>vuex-i18n</title>

	<script src='https://cdn.polyfill.io/v2/polyfill.min.js?flags=gated&unknown=polyfill'></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>
	<script src="https://unpkg.com/vuex@3.0.1"></script>

	<script src="../dist/vuex-i18n.min.js"></script>

	</head>
	<body>

		<div id="app">
			<div class="example-text"><h1>message.title: {{ $t('message.title') }}</h1></div>
		</div>

		<!-- application code -->
		<script type="text/javascript">

			// initialize a new vuex store including our i18nVuexModule
			const store = new Vuex.Store({});

			// initialize the vuexi18nPlugin
			Vue.use(vuexI18n.plugin, store);

			// define default translations for english text
			const localeEn = {
				'message.title': 'My translated title'
			};

			// add the english locale to the i18n store
			Vue.i18n.add('en', localeEn);

			// set the current language to english
			Vue.i18n.set('en');

			var app = new Vue({
				store: store,
				el: '#app'
			});

		</script>

	</body>
</html>
```

**Comment by tikiatua** [comment]
You also need to make sure, that only es5 javascript syntax is used in these older browsers.
