### ISSUE TITLE
Why rollup?

### ISSUE THREAD

**Issue by cbo317110** [dkfbasel/vuex-i18n#69]
I love webpack and webpack-dev-server, it is so simple, rollup looks simple too, but hasn't the same popularity that webpack has. Devs may gonna be a little confused (... ?)

Can you, just say, why you choosed rollup over webpack?

I perfect accept replies like "cause i wanted" or "cause i preffer it", but i want understand why you used it.

Thanks!

**Comment by tikiatua** [comment]
Hi @cbo317110,

We use webpack ourselves for all application projects and it is an awesome tool. Basically the configuration options for rollup were way simpler, which was the reason we chose it for this rather small library.

**Comment by tikiatua** [comment]
By the way, we created a specific docker container to use webpack (dkfbasel/hot-reload-webpack). https://github.com/dkfbasel/hot-reload

Webpack requires a huge amount of packages that need to be installed in every project directory and we felt a little uneasy with all the external code especially after reading this article https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5.

The approach with the separate docker container, allows us to check the output of all the packages with a minimal example and then apply it to all other projects. In addition, it makes it really easy to try to update webpack for a project.

**Comment by cbo317110** [comment]
Certainly i will take a look at it, thanks for your huge attention!
As a Webpack user since 2016, i never noticed it "fat", always noticed it "easy"

**Comment by cbo317110** [comment]
@tikiatua you have telegram, whatsapp, or something?

**Comment by tikiatua** [comment]
@cbo317110 I am somewhat conscious about providing contact information as I had some not so great experiences in the past. Feel free to drop me your contact email and I will get in touch with you.

**Comment by cbo317110** [comment]
@tikiatua cbo317110@gmail.com
