### ISSUE TITLE
Get fallback locale method?

### ISSUE THREAD

**Issue by simmons-kyle** [dkfbasel/vuex-i18n#70]
Is there a method available to retrieve the current fallback locale?

I can see we have fallback() as a method which calls the internal setFallbackLocale method but nothing exposed to get the fallback.

**Comment by tikiatua** [comment]
Hi @simmons-kyle 

Thank you for your question. All the plugin information is essentially stored in a vuex module (i18n by default). You can easily read out the current fallback locale using `this.$store.state.i18n.fallback`.

**Comment by simmons-kyle** [comment]
Great stuff, thanks for clarifying!
