### ISSUE TITLE
onTranslationNotFound enhancement make it get the fallback translation as a extra parameter

### ISSUE THREAD

**Issue by AlexanderYW** [dkfbasel/vuex-i18n#73]
what are your thought on making the onTranslationNotFound get the fallback translation as a extra parameter so i can let the server know what the user is getting viewed e.g.

`$t('header.username', 'The username is: {username}', {username: 'Bubbles'})`

`onTranslationNotFound (locale, key, fallback)` will result in:
locale: eg "en-US"
key: "header.username"
fallback: "The username is: {username}" <- this should not be parsed

**Comment by tikiatua** [comment]
Hi @AlexanderYW 

Thank you for your proposal. The onTranslationNotFound method does actually already receive the defaultValue as third argument.

```javascript
// vuex-i18n-plugin.js: line 172: invoke a method if a translation is not found
let asyncTranslation = onTranslationNotFound(locale, key, defaultValue);
```

```html
<div>
	// will return: "Default information text" if the key non.existing.key is
	// not specified in the current and the fallback locale
	{{ $t('non.existing.key', 'Default information text')}}
</div>
```

Please let me know if this will allow you to implement the functionality you are looking for.

**Comment by AlexanderYW** [comment]
I tried debugging it with `arguments`, but didn't get it, and neither did i when doing as you wrote, but i just realized that the reason it didn't work was because i was running `1.8.0`, don't know how it got that outdated...

Thanks for FAST support, and making me realized I made a beginner's mistake! :)
