### ISSUE TITLE
Error on Internet Explorer 11

### ISSUE THREAD

**Issue by Zambiorix** [dkfbasel/vuex-i18n#79]
I am getting the following error on Internet Explorer 11
My app runs fine on all other browsers ...

What could be the problem?

```
SCRIPT 438: Object doesn't support property or method 'assign'
152 (359,2)
```
Leading to the file: vuex-i18n.es.js

```
// merge default options with user supplied options
              var mergedConfig = Object.assign({
                           moduleName: 'i18n',
                           identifiers: ['{', '}'],
                           preserveState: false,
                           onTranslationNotFound: function onTranslationNotFound() {}
              }, config);
```

**Comment by tikiatua** [comment]
Hi @Zambiorix 

Object.assign is an es6 method that is not directly supported by IE 11. It is usually converted or polyfilled with babel when the code is compiled in webpack. You probably need to update your configuration for babel to specify which browsers to target.

**Comment by Zambiorix** [comment]
I added this simple test:

```
const object1 = {
  a: 1,
  b: 2,
  c: 3
};

const object2 = Object.assign({c: 4, d: 5}, object1);

console.log(object2.c, object2.d);
// expected output: 3 5

import Vue from 'vue'
import Vuex from 'vuex'
import VuexI18n from 'vuex-i18n'
Vue.use(Vuex)
Vue.use(VuexI18n.plugin, new Vuex.Store())
```

And indeed the assign seems to work, but still I get an error in vuex-i18n that assign is missing

I also installed:
`npm install --save-dev babel-plugin-transform-object-assign
`

And this is my babelrc
```
{
  "presets": [["es2015", {"modules": false}], "stage-2"],
  "plugins": ["transform-runtime", "transform-object-assign"],
  "comments": false
}
```

I have no idea what else I can do :-(

**Comment by tikiatua** [comment]
Could you please post your webpack config file. It could be possible that the vuex-i18n module is not compiled with babel, since it is in the node_modules folder.

Alternatively you could try to use the `import VuexI18n from 'vuex-i18n/dist/vuex-i18n.umd.js';` which contains a pre-transformed version.

**Comment by Zambiorix** [comment]
`
import VuexI18n from 'vuex-i18n/dist/vuex-i18n.umd.js'
`
Didn't change anything...

This is the babel-loader part of my webpack config (I am using Quasar framework 0.14):

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: ['/node_modules/vuex-i18n/',projectRoot],
        exclude: /node_modules/
      },
```

Originally the '/node_modules/vuex-i18n/' include part was not there, but I tried to add it to see if it works. It doesn't :-( 

I must exclude node_modules or the project does not build. Any other way to solve this?

(I really appreciate your help, btw ;-)

**Comment by Zambiorix** [comment]
Ok .. I solved this temporarily by moving the vuex-i18n.es.js file to my own project until I find a better solution..
(I have a deadline tomorrow 8am to have my project running :-)


Thanks for helping out!

**Comment by tikiatua** [comment]
I hope you can make your deadline tomorrow. I get the feeling. The last thing that you need then is to worry about some package in your pipeline that acts up. 

So, I take it that moving the vuex-i18n.es.js file directly into your project solved the problem. To me, this would really point towards a problem in the configuration of the compilation pipeline.

I would suggest to try to use `path.resolve` to match the directory name of vuex-i18n. Additionally it might be better not to use `exclude` together with the include directive. However, this would require the node_modules folder to be not in the same directory as your main application code. 

We usually structure our frontend directory like this
```
+ app (DIR)
+ node_modules (DIR)
- .babelrc
- .eslintrc
- package.json
- webpack.config.js
- yarn.lock
```

```javascript
// in webpack.config.js
var appDirectory = path.resolve(__dirname, 'app');
var vuexI18nDirectory = path.resolve(__dirname, 'node_modules/vuex-i18n');
// ...
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [appDirectory, vuexI18nDirectory]
},
```

**Comment by Zambiorix** [comment]
Without touching the rest of the build configuration, I just added 1 extra webpack rule.
It all works now...

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: projectRoot,
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: path.resolve(__dirname, '../node_modules/vuex-i18n/')
      },
```

**Comment by tikiatua** [comment]
Thank you for following up on this.

**Comment by alessandrobellesia** [comment]
In vue-cli you have to add 'vuex-18n' to transpileDependencies in vue.config.js

`module.exports = {
	transpileDependencies: ['vuex-i18n']
}`

**Comment by Jayin** [comment]
why not use [object-assign](https://github.com/sindresorhus/object-assign) to adapter ES5? 
As a library,it should not need user hack to much. 


BTW, are you using vux, I have same problem with like you.But this problem appear in Android WebView  @Zambiorix
