### ISSUE TITLE
removing locale always throws error ReferenceError: copy is not defined

### ISSUE THREAD

**Issue by prakashchokalingam** [dkfbasel/vuex-i18n#9]
On `  this.$i18n.remove(oldLang);` invoking remove the following error occurs 

`vuex-i18n.min.js?0fec:253 Uncaught (in promise) ReferenceError: copy is not defined`

Inspected the code the variable copy is not declared in the remove locale function

`	REMOVE_LOCALE: function REMOVE_LOCALE(state, payload) {

			// check if the given locale is present in the state
			if (state.translations.hasOwnProperty(payload.locale)) {

				// check if the current locale is the given locale to remvoe
				if (state.locale === payload.locale) {
					// reset the current locale
					state.locale = null;
				}

				// create a copy of the translations object
				var translationCopy = Object.assign({}, state.translations);

				// remove the given locale
				delete translationCopy[payload.locale];

				// set the state to the new object
				state.translations = copy;
			}
		}`

# state.translations = copy;

**Comment by tikiatua** [comment]
Hi @prakashchokalingam,

Thank you for reporting this. The line should actually be `state.translations = translationCopy;`. I added the respective fix in the branch tikiatua-patch-1 and will publish a new version to npm tomorrow.

**Comment by prakashchokalingam** [comment]
Thanks for the instant fix !

**Comment by tikiatua** [comment]
This should now be fixed in the latest npm version as well
