### ISSUE TITLE
Translate sentences

### ISSUE THREAD

**Issue by Ni55aN** [dkfbasel/vuex-i18n#94]
It may be useful to translate separately every sentence of the paragraph
It can be done with the help of next filter

```js
Vue.filter('stranslate', text => { // translate sentences
    if(!Vue.prototype.$t) throw 'Module vuex-i18n required';
    
    return text
        .split(/\. */g)
        .map(t => Vue.prototype.$t(t)) 
                   // or translate() function in scope of vuex-i18n-plugin.js
        .join('. ')
}); 
```

I can do a PR if this filter is useful for you

**Comment by tikiatua** [comment]
Hi @Ni55aN 

Thank you for your suggestion. I would like to keep the api of the vuexI18n-plugin rather small. There fore, I would suggest that we finally create a proper documentation and add this in an example section.

**Comment by tikiatua** [comment]
Hi @Ni55aN 

Thank you for following up on this. I will likely not implement this feature directly into the library. In my opinion, the context of adjoint sentences often matters and therefore one should not just concatenate separate translations. Additionally translating one string could have unintended side-effects in a different part of the application.

That is also one of the reasons, that I do not think it should be possible to reference from one translation string to another – i.e. something like {sentence: "this is a translation of [email]", email: "message"} – which is implemented by other libraries.

However, a similar feature would be the possibility to have complete text blocks or even html content with included vue components as a translation element. I will look into how this can be achieved without compromising security too much. 

An update in this direction should be available sometime in November.
