### ISSUE TITLE
Access to current local in a getters module's vuex

### ISSUE THREAD

**Issue by alex83130** [dkfbasel/vuex-i18n#96]
Hi, I would access to the current local in getters of a module's vuex.
Normaly the getter sould be : 
`rootGetters['i18n/locale']`
But it's not recognized... I have display the rootGetters array and there is'nt namespaced i18n.

Have you a issue ?

Thanks in advance !

**Comment by tikiatua** [comment]
Hi @alex83130 

Thank you for your request. What exactly are you trying to do? You can access the vuex store without using any getters. To access the data from the i18n-module you would just use this.$store.state.i18n or rootState.i18n.

**Comment by alex83130** [comment]
Thanks it's ok :)
