### ISSUE TITLE
Option to suppress the `i18n: Not all placeholders found` console warnings

### ISSUE THREAD

**Issue by dmcdonald8** [dkfbasel/vuex-i18n#99]
I have some strings in the Vuex store that need translated and contain placeholders e.g `{0} {1}`

However due to the way they're implemented the placeholder actual values are not provided at translation time but are inserted later

I would like an option to disable the console warnings whenever this happens as its not going to change any time soon. 

I can see in vuex-i18n-plugin.js
```// define the replacement function
	let replace = function replace(translation, replacements, warn = true) {
         ...
         if (warn === true) {
	    console.group ? console.group('i18n: Not all placeholders found') : console.warn('i18n: Not all 
            placeholders found');```


//some way to set the value of `warn` argument would be ideal

**Comment by tikiatua** [comment]
Hi @dmcdonald8 

Thank you for reporting. the issue. This can easily be implemented. Stay tuned.
